### PR TITLE
Revert "Beautify"

### PR DESCRIPTION
**Pull request by ggobugi27**
Reverts kadena-community/kadena-transfer-js#9

### CODE REVIEW

**Comment by ggobugi27** [comment]
@Thanos420NoScope Could you actually add the icon to html files in /docs folder please? Thanks!

**Comment by ggobugi27** [comment]
@fmelp Can `index.html` in root folder be deleted?

**Comment by Thanos420NoScope** [comment]
I used img to be consistent with other Kadena repos. Not sure why docs would be better?

**Comment by ggobugi27** [comment]
@Thanos420NoScope 

This tool is hosted via github pages, and it builds the website from the `/docs` folder. I added the icon from [https://explorer.chainweb.com](https://explorer.chainweb.com) in #8 .

**Pull request closed without merging**
